### GET ALL GAMES
GET http://localhost:8080/api/v1/games/
Authorization: Basic admin 123456
Accept: application/json

###

### GET ONE GAME
GET http://localhost:8080/api/v1/games/67e7f25cef79d0581d7594fa
Authorization: Basic admin 123456
Accept: application/json
###

### DELETE ONE GAME
DELETE http://localhost:8080/api/v1/games/3
Authorization: Basic admin:123456
Accept: application/json
###

### CREATE ONE GAME
POST http://localhost:8080/api/v1/games
Authorization: Basic admin 123456
Content-Type: application/json

{
  "name": "TLOU",
  "description": "The Last Of Us",
  "sells": 1000000
}



### UPDATE ONE GAME
PUT http://localhost:8080/api/v1/games/0
Authorization: Basic admin 123456
Content-Type: application/json

{
  "id": "2",
  "name": "GOW",
  "description": "God Of War",
  "sells": 2000000
}


###

